### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by peternavr** [go-gremlin/gremlin#5]
How do you authenticate?

**Comment by rushmorem** [comment]
Unfortunately, this driver doesn't support authentication yet.

**Comment by peternavr** [comment]
Do you have any docs on this?

**Comment by rushmorem** [comment]
You mean for the driver? Currently it's just the readme and [Godoc](https://godoc.org/github.com/go-gremlin/gremlin) but there is not much going on. It should be easy to follow.

**Comment by peternavr** [comment]
I have no problem trying to implement the spec for Auth, but I don't know where it is. Could you point me in the right direction?

**Comment by rushmorem** [comment]
You can refer to [the docs for v3.0.2](http://tinkerpop.apache.org/docs/3.0.2-incubating/#_developing_a_driver). I can't quickly find out where the docs for v3.2.x are located.

**Comment by LeeWong** [comment]
Any update on this issue? Thanks.

**Comment by adrpino** [comment]
@rushmorem I've got an almost working version of this, but it would imply breaking changes in your existing Api. Are you extremely strict about that?
